print ('Quer saber a tabuada de algum número')
n= int(input('Aeeee, digite qualquer número:'))
print (f'{n}x1= {n}')
print (f'{n}x2= {n*2}')
print (f'{n}x3= {n*3}')
print (f'{n}x4= {n*4}')
print (f'{n}x5= {n*5}')
print (f'{n}x6= {n*6}')
print (f'{n}x7= {n*7}')
print (f'{n}x8= {n*8}')
print (f'{n}x9={n*9}')
print (f'{n}x10= {n*10}')
print (f'Essa é a taboada do {n}')