print('Vamos ver o tipo primitivo e todas as informações possíveis em algo que voce digite?')
n1= input('Digite algo, jovem garfanhoto!')
print('O tipo primitivo desse valor é:', type(n1))
print('Só tem espaços?', n1.isspace())
print('É um número?', n1.isnumeric())
print('É alfabético?', n1.isalpha())
print('É alfanúmerico', n1.isalnum())
print('Está com letras minúsculas?', n1.islower())
print('Está com letras maiúsculas?', n1.isupper())
